inference:
  model:
    name: VisionTransformer

  score: f1 # f1, acc, epoch5

  # 학습한 모델과 동일한 설정을 사용해야 합니다!
  # cutout은 진행되지 않습니다!
  augmentation:
    name: RandomAugTransform
    args:
      resize: 512
      cutout: 130
      n: 3
      m: 0.5

  # 공식 문서에 있는 설정을 더 추가할 수 있습니다
  data_loader:
    batch_size: 64
    shuffle: False
    drop_last: False

  TTA:
      flag: True

inferencer:
  csv_path: /opt/ml/input/data/eval/info.csv
  img_path: /opt/ml/input/data/eval/images
  model_dir: ./model_weights/ViT-adamw-b32
  save_dir: ./output